name: SmartDesk Backend CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      SECRET_KEY: "0123456789abcdef0123456789abcdef"
      MONGO_URI: "mongodb://127.0.0.1:27017"
      MONGO_DB: "smartdesk_test"


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Linter
        run: ruff check . --output-format=github

      - name: Check Ruff Formatting
        run: ruff format --check .

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest